pipeline {

  agent {
       docker {
          label 'demo-docker'
          image 'bibinwilson/jenkins-slave:latest'
          } 
    }

stages {
        stage('Build') {
            steps {
                echo 'Hello, this is the Build stage!'
            }
        }
    }
}
