pipeline {
    agent {
      label 'docker-slave-agent'
    } 

    
environment {
        REGISTRY = "shantanu1990"
        IMAGE_NAME = "nodejs-app"
        DOCKER_IMAGE = "${REGISTRY}/${IMAGE_NAME}"
	}
		
    stages {
        stage('Checkout') {
            steps {
                 checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ShantanuParanjpe/k8s-deploy']])
            }
        }
        
	stage('Build docker image') {
            agent {
                docker {
                    image 'docker:24.0.6'       
                    args '--entrypoint="" -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }

            steps {
                script {
                    sh '''
                      docker build -t ${DOCKER_IMAGE} node-js-project/ 
		      '''	
                       }
		}	

            }
	
      stage('Login to DockerHub') {
            steps {
               script {
                  withCredentials([usernamePassword(credentialsId: 'docker-token', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                  sh 'echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin'
               }
           }
      }
  }
	
        stage('Push Docker') {
            steps {
                script {            
                   sh "docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}"
                }
            }
        }
    }    
}	
