---
- name: Deploy NGINX Application
  hosts: tag_Name_k8s_master 
  become: true
  tasks:
    - name: Deploy NGINX Deployment
      k8s:
        api_version: apps/v1
        kind: Deployment
        name: nginx-deployment
        namespace: default
        spec:	
          selector:
            matchLabels:
              app: nginx
          replicas: 3
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: nginx 
                  ports:
                    - containerPort: 80
 
    - name: Deploy NGINX Service
      k8s:
        api_version: v1
        kind: Service
        name: nginx-service
        namespace: default
        selector:
          app: nginx
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 80
        type: LoadBalancer 
