---
- name: Create Secret object
  hosts: tag_Name_k8s_client 
  gather_facts: false
  tasks:
    - name: Read daemon.json from Jenkins credential
      ansible.builtin.slurp:
        src: "/var/lib/jenkins/credentials/docker-auth/daemon.json"
      register: daemin_json_data
    
    - name: Create Docker Config Secret
      community.kubernetes.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: docker-config-secret
          data:
            .dockerconfigjson: "{{ daemon_json_data.content | b64encode }}"
        state: present
